services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - fastapi_network
    restart: always

networks:
  fastapi_network:
    driver: bridge

